name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    if: github.repository_owner == 'imaginefun'
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: publish to modrinth and github
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: imaginefunutils
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-tag: ${{ github.event.release.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: build/libs/!(*-@(dev-shadow|sources|javadoc|)).jar
          name: ImagineFunUtils ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}
          version-type: release
          loaders: fabric
          game-versions: 26.1
